Repository Git-For-Geeks/String-operation, pull requests merged in 2022-10, with the labels that each got.

#8 Added word counter
  index.html
Labels: git-for-geeks, easy

#9 added toUpperCase operation
  index.html
Labels: git-for-geeks, easy, hacktoberfest

#10 tolowercase
  index.html
Labels: git-for-geeks, easy

#15 Added 2 fundtion searchWord and replaceString
  index.html
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#21 Added Funtionality to remove extra spaces
  index.html
Labels: git-for-geeks, medium
